#ifndef POOL_SPMD_H
#define POOL_SPMD_H

#include "pool.h"

DLL_EXPORT void spmd_4x_linear(
    double *col1_rvw1, double *col1_rvw2,
    double *col2_rvw1, double *col2_rvw2,
    double *col3_rvw1, double *col3_rvw2,
    double *col4_rvw1, double *col4_rvw2,
    float R,
    float M,
    float u_s1,
    float u_s2,
    float col1_u_b,
    float col2_u_b,
    float col3_u_b,
    float col4_u_b,
    float e_b,
    float deltaP,
    int N,
    double *col1_rvw1_result, double *col1_rvw2_result,
    double *col2_rvw1_result, double *col2_rvw2_result,
    double *col3_rvw1_result, double *col3_rvw2_result,
    double *col4_rvw1_result, double *col4_rvw2_result,
    Profile *profiles, Branch *branchs);
DLL_EXPORT void spmd_4x_recip_sqrt(
    double *col1_rvw1, double *col1_rvw2,
    double *col2_rvw1, double *col2_rvw2,
    double *col3_rvw1, double *col3_rvw2,
    double *col4_rvw1, double *col4_rvw2,
    float R,
    float M,
    float u_s1,
    float u_s2,
    float col1_u_b,
    float col2_u_b,
    float col3_u_b,
    float col4_u_b,
    float e_b,
    float deltaP,
    int N,
    double *col1_rvw1_result, double *col1_rvw2_result,
    double *col2_rvw1_result, double *col2_rvw2_result,
    double *col3_rvw1_result, double *col3_rvw2_result,
    double *col4_rvw1_result, double *col4_rvw2_result,
    Profile *profiles, Branch *branchs);
DLL_EXPORT void spmd_basic_collide_balls(
    double *col1_rvw1, double *col1_rvw2,
    double *col2_rvw1, double *col2_rvw2,
    double *col3_rvw1, double *col3_rvw2,
    double *col4_rvw1, double *col4_rvw2,
    float R,
    float M,
    float u_s1,
    float u_s2,
    float col1_u_b,
    float col2_u_b,
    float col3_u_b,
    float col4_u_b,
    float e_b,
    float deltaP,
    int N,
    double *col1_rvw1_result, double *col1_rvw2_result,
    double *col2_rvw1_result, double *col2_rvw2_result,
    double *col3_rvw1_result, double *col3_rvw2_result,
    double *col4_rvw1_result, double *col4_rvw2_result,
    Profile *profiles, Branch *branches);

#endif
